name: webmonchow
channels:
  - conda-forge
dependencies:
  - python>=3.10  # please specify the minimum version of python here
  - pip
  - psycopg2
  - stomp.py
  - versioningit
  # Development dependencies
  - pre-commit
  - libmamba
  - libarchive
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - twine
  - sphinx
  - sphinx_rtd_theme
  - myst-parser  # required for parsing markdown files
  - pytest
  - pytest-cov
#  - pip:
#      - some_package
